config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :payments, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  end

  devise_scope :user do
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
    
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  end
end

app/models/group_payment.rb
class GroupPayment < ApplicationRecord
  belongs_to :group, foreign_key: 'group_id', class_name: 'Group'
  belongs_to :payment, foreign_key: 'payment_id', class_name: 'Payment'
end

app/controllers/group_payments_controller.rb
class GroupPaymentsController < ApplicationController
  before_action :set_group_payment, only: %i[show edit update destroy]

  # GET /group_payments or /group_payments.json
  def index
    @group_payments = GroupPayment.all
  end

  # GET /group_payments/1 or /group_payments/1.json
  def show; end

  # GET /group_payments/new
  def new
    @group_payment = GroupPayment.new
  end

  # GET /group_payments/1/edit
  def edit; end

  # POST /group_payments or /group_payments.json
  def create
    @group_payment = GroupPayment.new(group_payment_params)

    respond_to do |format|
      if @group_payment.save
        format.html { redirect_to group_payment_url(@group_payment), notice: 'Group payment was successfully created.' }
        format.json { render :show, status: :created, location: @group_payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_payments/1 or /group_payments/1.json
  def update
    respond_to do |format|
      if @group_payment.update(group_payment_params)
        format.html { redirect_to group_payment_url(@group_payment), notice: 'Group payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_payments/1 or /group_payments/1.json
  def destroy
    @group_payment.destroy

    respond_to do |format|
      format.html { redirect_to group_payments_url, notice: 'Group payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group_payment
    @group_payment = GroupPayment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_payment_params
    params.fetch(:group_payment, {})
  end
end

app/helpers/group_payments_helper.rb
module GroupPaymentsHelper
end

app/views/group_payments/_form.html.erb
<%= form_with(model: @payment, url: group_payments_path, method: :post) do |form| %>
  <% if group_payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group_payment.errors.count, "error") %> prohibited this group_payment from being saved:</h2>

      <ul>
        <% group_payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/group_payments/_group_payment.html.erb
<div id="<%= dom_id group_payment %>">
</div>

app/views/group_payments/edit.html.erb
<h1>Editing group payment</h1>

<%= render "form", group_payment: @group_payment %>

<br>

<div>
  <%= link_to "Show this group payment", @group_payment %> |
  <%= link_to "Back to group payments", group_payments_path %>
</div>

app/views/group_payments/index.html.erb
<h1>Group payments</h1>

<div id="group_payments">
  <% @group_payments.each do |group_payment| %>
    <%= render group_payment %>
    <p>
      <%= link_to "Show this group payment", group_payment %>
    </p>
  <% end %>
</div>

<%= link_to "New group payment", new_group_group_payment_path %>

app/views/group_payments/new.html.erb
<h1>New transaction</h1>

<%= render "form", group_payment: @group_payment %>

<br>

<div>
  <%= link_to "Back to category", groups_path %>
</div>

app/views/group_payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_payment %>

<div>
  <%= link_to "Edit this group payment", edit_group_payment_path(@group_payment) %> |
  <%= link_to "Back to group payments", group_payments_path %>

  <%= button_to "Destroy this group payment", @group_payment, method: :delete %>
</div>