config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :payments, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  end

  devise_scope :user do
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
    
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id', class_name: 'User'
  has_many :group_payments, dependent: :destroy
  has_many :payments, through: :group_payments, dependent: :destroy

  validates :name, presence: true

  def total_amount
    payments.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @user = current_user
    @groups = Group.where(author_id: @user.id).includes(:group_payments)
  end

  def show
    @group = Group.find(params[:id])
    @payments = @group.payments.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)
    @group.author_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    payments = []
    group_payments = @group.group_payments.all
    group_payments.each do |e|
      payment = Payment.find_by(id: e.payment_id)
      payments.push(payment)
    end

    group_payments.destroy_all
    payments.each(&:destroy)
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def icon_links()
    [
      'https://cdn-icons-png.flaticon.com/512/3514/3514242.png',
      'https://cdn-icons-png.flaticon.com/512/3514/3514424.png',
      'https://cdn-icons-png.flaticon.com/512/4435/4435747.png',
      'https://cdn-icons-png.flaticon.com/512/4490/4490059.png',
      'https://cdn-icons-png.flaticon.com/512/4490/4490127.png',
      'https://cdn-icons-png.flaticon.com/512/8041/8041915.png',
      'https://cdn-icons-png.flaticon.com/512/3277/3277187.png',
      'https://cdn-icons-png.flaticon.com/512/3258/3258593.png',
      'https://cdn-icons-png.flaticon.com/512/2391/2391669.png',
      'https://cdn-icons-png.flaticon.com/512/2376/2376471.png',
      'https://cdn-icons-png.flaticon.com/512/2221/2221802.png',
      'https://cdn-icons-png.flaticon.com/512/2221/2221828.png',
      'https://cdn-icons-png.flaticon.com/512/2149/2149723.png',
      'https://cdn-icons-png.flaticon.com/512/2084/2084845.png',
      'https://cdn-icons-png.flaticon.com/512/2053/2053603.png',
      'https://cdn-icons-png.flaticon.com/512/2053/2053561.png',
      'https://cdn-icons-png.flaticon.com/512/1791/1791258.png',
      'https://cdn-icons-png.flaticon.com/512/1567/1567218.png',
      'https://cdn-icons-png.flaticon.com/512/1567/1567225.png',
      'https://cdn-icons-png.flaticon.com/512/873/873888.png'
    ]
  end
end

app/views/groups/_form.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "links.js" %>
<% end %>

<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div class="field">
    <%= form.text_field :icon, placeholder: "Link to icon", class: "icon_link" %>
  </div>

  <h2> Input the link to icon image, or select the one from below:</h2>

  <div class="group-links">
    <% icon_links.each do |link| %>
      <div>
        <img class="group-image" src="<%= link %>" alt="icon" onclick="selectLink('<%= link %>')"/>
      </div>
    <% end %>
  </div>

  <div class="pleaseholder"></div>

  <div class="btn-bottom">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="group-item" id="<%= dom_id group %>">
  <img class="group-image" src="<%= group.icon %>" alt=<%= group.name %>/>
  <div class="group-details">
    <p>
      <%= group.name %>
    </p>

    <p>
      $<%= group.total_amount%>
    </p>
  </div>
</div>

app/views/groups/edit.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", @group, class: "link-header" %>
  <p class="header-title">Editing group</p>
</nav>

<%= render "form", group: @group %>

app/views/groups/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "menu.js" %>
<% end %>

<section class="group">
  <nav class="nav-menu">
    <div class="nav-menu-details">
      <span class="std-color">
        <img class="profile-image"
        alt="profile menu icon"
        src="<%= asset_path('profile-icon.png') %>">
      </span>

      <span class="std-color">
        <% if user_signed_in? %> 
          <%= current_user.name %>
        <% end %>
      </span class="std-color">
      <%= button_to "SIGN OUT", destroy_user_session_path, method: :delete, class: "btn-signout" %>

      <div class="std-color">
        <p class="nav-menu-row"><strong class="nav-menu-row">Total: $<%= total_user_amount %></strong></p>
        <% @groups.each do |group| %>
          <p class="nav-menu-row"><%= group.name%>: <%= (100 * group.total_amount / total_user_amount).round(1) %>%</p>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="group-index">
    <div class="group-header">
      <nav class="group-navbar">
        <img class="burger-image"
          alt="burger menu icon"
          onclick="showMenu()"
          src="<%= asset_path('hamburger-icon.png') %>">
      </nav>
      <p class="header-title">CATEGORIES</p>
    </div>

    <div class="group-container" id="groups">
      <% @groups.each do |group| %>
        <%= link_to group_path(group.id), class: "group-link" do %>
          <%= render group %>
        <% end %>
      <% end %>
    </div>

    <div class="footer">
      <%= link_to "ADD CATEGORY", new_group_path, class: "btn-bottom" %>
    </div>
  </div>
</section>

app/views/groups/new.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", groups_path, class: "link-header" %>
  <p class="header-title">New category</p>
  <p></p>
</nav>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", groups_path, class: "link-header" %>
  <%= link_to "EDIT", edit_group_path(@group), class: "link-header" %>
  <%= button_to "REMOVE", @group, method: :delete, class: "btn-header" %>
</nav>

<%= render @group %>

<div class="payments-index">
  <div class="payments-container">
    <% @payments.each do |payment| %>
      <%= link_to group_payment_path(@group.id, payment.id), class: "group-link" do %>
        <div class="payments-item">
          <div class="payment-info">
            <p><%= payment.name %></p>
            <p><%= payment.created_at %></p>
          </div>
          <p>$<%= payment.amount %></p>
        </div>
      <% end %> 
    <% end %> 
  </div>
</div>

<div>
  <%= button_to "ADD TRANSACTION", new_group_payment_path(@group.id), method: :get, class: "btn-bottom" %>
</div>