config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :payments, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  end

  devise_scope :user do
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
    
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id', class_name: 'User'
  has_many :group_payments, dependent: :destroy
  has_many :groups, through: :group_operations

  validates :name, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_payment, only: %i[show edit update destroy]

  def index
    @group_id = params[:group_id]
    @payments = Payment.all
  end

  def show
    @group = Group.find(params[:group_id])
  end

  def new
    @group_id = params[:group_id]
    @payment = Payment.new
  end

  def edit
    @group = Group.find(params[:group_id])
    @payment = Payment.find(params[:id])
  end

  def create
    @user = current_user
    @payment = Payment.new(payment_params)
    @payment.author_id = @user.id

    if @payment.save
      @group_id = params[:group_id]
      @group_payment = GroupPayment.new(group_id: @group_id, payment_id: @payment.id)

      if @group_payment.save
        redirect_to group_url(@group_id), notice: 'Payment was successfully created.'
      else
        flash[:alert] = 'Group payment couldn`t be saved'
        redirect_to new_group_payment_url(@group_id)
      end
    else
      flash[:alert] = 'Transaction couldn`t be saved, please check name and amount'
      @group_id = params[:group_id]
      redirect_to new_group_payment_url(@group_id)
    end
  end

  def update
    @group = Group.find(params[:group_id])
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @payment.group_payments.destroy_all
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to group_url(@group), notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, url: group_payments_path, method: :post) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div class="field">
    <%= form.number_field :amount, placeholder: "Amount, $", step: "0.01" %>
  </div>
  
  <br>

  <div class="btn-bottom">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div class="payment-row" id="<%= dom_id payment %>">
  <br>
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Transaction N </strong>
    <%= payment.id %>
  </p>

  <p>
    <strong></strong>
    <%= payment.created_at %>
  </p>

  <p>
    <strong>TOTAL PAYMENT:</strong>
    $<%= payment.amount %>
  </p>

</div>

app/views/payments/edit.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", group_path(@group), class: "link-header" %>
  <p class="header-title">Editing payment</p>
  <p></p>
</nav>

<%= render "form", payment: @payment %>

app/views/payments/index.html.erb
<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", group_payments_path(payment.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", group_url(@group_id), class: "link-header" %>
  <p class="header-title">New transaction</p>
  <p></p>
</nav>

<%= render "form", payment: @payment %>

app/views/payments/show.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", group_path(@group), class: "link-header" %>
  <%= link_to "COPY", edit_group_payment_path(@group, @payment), class: "link-header" %>
  <%= button_to "REMOVE", @group_payment, method: :delete, class: "btn-header" %>
</nav>

<%= render @payment %>